### ISSUE TITLE
Keyboard command not working to open links.

### ISSUE THREAD

**Issue by rkingett** [enafore/enafore#11]
Some webpages linked in posts don't open when you press L. I'm not sure why this might be happening.
The link below is to a post where this occurs.

https://mastodon.toptechtidbits.com/@news/111895519380260550

running Enafore version v56-8d7914fc.

**Comment by easrng** [comment]
The L hotkey is specifically for posts with a link preview card and that post doesn't have one. (Well, technically it does, but Enafore won't render it because it also has an attached file.)
