### ISSUE TITLE
Unhandled notification type "mention"

### ISSUE THREAD

**Issue by Svenja001** [enafore/enafore#12]
I run Version v56-8d7914fc.  The subjected Message came up when I read through my Mentions, it seems to be deleted mentions, because I can't see them on the Original Mastodon Client and on Enafore its only showing the Error Unhandled notification type "mention" and a Link to report that.

**Comment by easrng** [comment]
What instance are you on?

**Comment by Svenja001** [comment]
its fedisabled.social

**Comment by easrng** [comment]
looking into this and yeah it seems like it happens when you get an empty mention notification. probably should be reported to the mastodon folks.
