### ISSUE TITLE
Filtering not applied to alt texts

### ISSUE THREAD

**Issue by tuxwise** [enafore/enafore#13]
Steps to reproduce:

1. Pick a post from your local timeline with an image that contains a word in its alt text that is not mentioned in the post itself. E.g., the word "Himmel" in [this post](https://social.tchncs.de/@Sunnypug/112315750354979244)
2. Define a filter, containing keyword "Himmel", select that it applies to public timelines, and activate "Hide completely"
3. Log in both via enafore as well as via the standard Mastodon web frontend
4. **Look at the local timeline via enafore: the post is still visible.**
5. **Look at "Live feeds" > "This server" via the standard Mastodon web frontend: the post is suppressed.**

**Comment by rkingett** [comment]
I can reproduce this on my instance, which is running Glitch.

**Comment by easrng** [comment]
Fixed!
