### ISSUE TITLE
older Notifications not showing anymore in Version v61-db18ee05. 

### ISSUE THREAD

**Issue by Svenja001** [enafore/enafore#14]
if I open Enafore I can no longer see Notifications on "all", only if I filter Mentions the previously gotten mentions appear, switching back to "all" it looks like there were no Notifications at all in the past.
If this is intentional, I'd suggest a Setting where the User could choose if they want to see past Notifications or not.

**Comment by easrng** [comment]
That's definitely not intentional. I can't reproduce that issue on the Mastodon instance I test with, could you check if there are any errors in the javascript console?

**Comment by easrng** [comment]
Hmm maybe I should add a way to get logs within the interface like bluesky has...

**Comment by Svenja001** [comment]
seems to have fixed itself, it now works again

**Comment by Svenja001** [comment]
ah I have the Error again, unfortunately parts of the log are in German, but I wanted to safe it here anyway to not forget it myself its something about a blocked Inlinescript: 

Content-Security-Policy: Die Einstellungen der Seite haben die Ausführung eines Inline-Skripts (script-src-elem) blockiert, da es gegen folgende Direktive verstößt: "script-src 'self' 'sha256-z4sZJzG54hJKeFb690QLe/ysJeUFUgyjxE3cmoakQ0o=' 'sha256-Rv0XCoOhq4H0QyKE7rEhr+e9GI5gsmGcC04fY0HPORc=' 'sha256-28NJWgGMi7z1BsySG4SYZCjth/ys7dkElS3oIl5ZEqM=' 'sha256-nUHIts9QUqQq4nfffteH1WG3ZeWESwmxZn6bWMNWsiM=' 'sha256-MGLg9fH15qQqEcT+iTfwx/cfVp2MgjSrVt08u3NVKa8=' 'sha256-OQjxgqHHnjfZwkCEsAo2MRjd3GuPmg+RvmjrZd35TN4=' 'sha256-sS3nggZVNGyoYqI7U/PSwnwI4CymIdHNgJwW49qztWo=' 'sha256-aASq1hOJ8PP2cfK9QGXaCLdqgtkDXDb5VFXlSyrpX/M=' 'sha256-1ujkGrbsh0Yx/bquh2I9gkG1ZaZetCkjre6vciK2u7U='" sandbox eval code:107:351 
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://fedisabled.social/nodeinfo/2.0. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200. 
got error fetching nodeInfo TypeError: NetworkError when attempting to fetch resource. instance.js:23:12 
Uncaught (in promise) TypeError: n.media_attachments is undefined 
    o createSearchIndexFromStatusOrNotification.js:10 
    s computeFilterContextsForStatusOrNotification.js:9 
    s timelineItemToSummary.js:19 
    a timelineItemToSummary.js:24 
    i timeline.js:164 
    A timeline.js:164 
    A timeline.js:204 
2 createSearchIndexFromStatusOrNotification.js:10:195 
Uncaught (in promise) TypeError: n.media_attachments is undefined 
    o createSearchIndexFromStatusOrNotification.js:10 
    s computeFilterContextsForStatusOrNotification.js:9 
    s timelineItemToSummary.js:19 
    a timelineItemToSummary.js:24 
    i timeline.js:164 
    A timeline.js:164 
    A timeline.js:204 
    B timeline.js:225 
    ee Timeline.html:60 
    ne 5344.5bd65b5ebe02b3965c7b.5344.js:1 
    te shared.js:1056 
    J shared.js:972 
    Z shared.js:1013 
    o LazyTimeline.html:27 
    l 4031.eed68498ab61589088ae.4031.js:1 
    te shared.js:1056 
    J shared.js:972 
    Z shared.js:1013 
    r LazyPage.html:19 
    r LazyPage.html:19 
    a doubleRAF.js:2 
    a doubleRAF.js:2 
    r LazyPage.html:19 
    c 3084.da42ce81b61347772c6c.3084.js:1 
    te shared.js:1056 
    J shared.js:972 
    Z shared.js:1013 
    le client.js:579 
    ce client.js:554 
    promise callback*ce client.js:543 
    M client.js:9 
    goLeftOrRight NavShortcuts.html:59 
    h NavShortcuts.html:15 
    z shared.js:961 
    onKeyDown Shortcut.html:23 
    _ shortcuts.js:118 
    g shortcuts.js:104 
    b shortcuts.js:130 
createSearchIndexFromStatusOrNotification.js:10:195

**Comment by easrng** [comment]
Thanks! The inline script error isn't a big deal, nor is the nodeinfo warning (that's expected on mastodon instances actually, I'll update the code to reflect that.)
I think I know what the problem is!

**Comment by easrng** [comment]
Should be fixed in v64, let me know if it's still an issue!
