### ISSUE TITLE
Post not loading when opening them from Timeline

### ISSUE THREAD

**Issue by Svenja001** [enafore/enafore#15]
Since a few Days, when I look through my Home Timeline, several Posts are not showing if I open them. Its sometimes happening, sometimes not, so I had a hard Time to reproduce it, but here is what my Console said
If I understand it right it has to do with Neworkerrors, but I saw a Post from someone else today having the same Issue, so I'd report it

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://fedisabled.social/nodeinfo/2.0. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.
got error fetching nodeInfo TypeError: NetworkError when attempting to fetch resource. instance.js:23:12
Uncaught (in promise) TypeError: n.media_attachments is undefined
    o createSearchIndexFromStatusOrNotification.js:10
    s computeFilterContextsForStatusOrNotification.js:9
    s timelineItemToSummary.js:19
    a timelineItemToSummary.js:24
    i timeline.js:164
    A timeline.js:164
    A timeline.js:204
    B timeline.js:225
    ee Timeline.html:60
    ne 5344.5bd65b5ebe02b3965c7b.5344.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    o LazyTimeline.html:27
    l 4031.eed68498ab61589088ae.4031.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    r LazyPage.html:19
    r LazyPage.html:19
    a doubleRAF.js:2
    a doubleRAF.js:2
    r LazyPage.html:19
    c 3084.da42ce81b61347772c6c.3084.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    le client.js:579
    ce client.js:554
    promise callback*ce client.js:543
    M client.js:9
    open Status.html:289
    onClickOrKeydown Status.html:284
    za Status.html:215
    W delegate.js:31
createSearchIndexFromStatusOrNotification.js:10:195
Uncaught (in promise) TypeError: i is undefined
    E timeline.js:263
    o Timeline.html:195
    u scheduleIdleTask.js:33
    requestIdleCallback handler*d scheduleIdleTask.js:52
    setupStreaming Timeline.html:216
    o svelte-extras.es.js:188
    z shared.js:961
    X shared.js:1034
    Z shared.js:1011
    _set store.js:82
    _set store.js:81
    set store.js:170
    setForTimeline timelineMixins.js:15
    d addStatusOrNotification.js:36
    h addStatusOrNotification.js:91
    h addStatusOrNotification.js:100
    u scheduleIdleTask.js:33
    requestIdleCallback handler*d scheduleIdleTask.js:52
    h addStatusOrNotification.js:99
    g addStatusOrNotification.js:114
    w timeline.js:52
    w timeline.js:81
    c timeline.js:94
    T timeline.js:148
    A timeline.js:203
    B timeline.js:225
    ee Timeline.html:60
    ne 5344.5bd65b5ebe02b3965c7b.5344.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    o LazyTimeline.html:27
    l 4031.eed68498ab61589088ae.4031.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    r LazyPage.html:19
    r LazyPage.html:19
    a doubleRAF.js:2
    a doubleRAF.js:2
    r LazyPage.html:19
    c 3084.da42ce81b61347772c6c.3084.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    le client.js:579
    ce client.js:554
    promise callback*ce client.js:543
    M client.js:9
    open Status.html:289
    onClickOrKeydown Status.html:284
    za Status.html:215
    W delegate.js:31
timeline.js:263:34
    E timeline.js:263
    o Timeline.html:195
    u scheduleIdleTask.js:33
    (Async: requestIdleCallback handler)
    d scheduleIdleTask.js:52
    setupStreaming Timeline.html:216
    o svelte-extras.es.js:188
    z shared.js:961
    X shared.js:1034
    Z shared.js:1011
    _set store.js:82
    forEach self-hosted:203
    _set store.js:81
    set store.js:170
    setForTimeline timelineMixins.js:15
    d addStatusOrNotification.js:36
    AsyncFunctionNext self-hosted:852
    (Async: async)
    h addStatusOrNotification.js:91
    h addStatusOrNotification.js:100
    u scheduleIdleTask.js:33
    (Async: requestIdleCallback handler)
    d scheduleIdleTask.js:52
    h addStatusOrNotification.js:99
    g addStatusOrNotification.js:114
    w timeline.js:52
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    w timeline.js:81
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    c timeline.js:94
    T timeline.js:148
    A timeline.js:203
    B timeline.js:225
    ee Timeline.html:60
    ne 5344.5bd65b5ebe02b3965c7b.5344.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    o LazyTimeline.html:27
    AsyncFunctionNext self-hosted:852
    (Async: async)
    l 4031.eed68498ab61589088ae.4031.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    r LazyPage.html:19
    (Async: FrameRequestCallback)
    r LazyPage.html:19
    (Async: FrameRequestCallback)
    a doubleRAF.js:2
    (Async: FrameRequestCallback)
    a doubleRAF.js:2
    r LazyPage.html:19
    c 3084.da42ce81b61347772c6c.3084.js:1
    te shared.js:1056
    J shared.js:972
    Z shared.js:1013
    le client.js:579
    ce client.js:554
    (Async: promise callback)
    ce client.js:543
    M client.js:9
    open Status.html:289
    onClickOrKeydown Status.html:284
    za Status.html:215
    W delegate.js:31

**Comment by easrng** [comment]
same issue as #14, which should be fixed now.
