### ISSUE TITLE
Unhandled notification type `status` (GTS subscribed post notifications)

### ISSUE THREAD

**Issue by ewwwin** [enafore/enafore#36]
I use Enafore against the instance https://tired.umbreon.online, which runs GoToSocial 0.15.0+git-15733cd. (I haven't gotten around to upgrading to 0.16 yet, though I don't see any indication in the release notes that the reported notification type has changed between these versions.) This notification type appears when an account you've subscribed to makes a new post. Prior to the recent update which included notification grouping, these came up as generic notifications with a bell icon and a generic title.

![screenshot of an enafore notification which says "Unhandled notification type status" with a question mark icon and a "Report" button, followed by a post made by a user i am subscribed to](https://github.com/user-attachments/assets/a44b5ca5-18e3-4d5b-bc95-ffb69e91afd2)

Firefox 121.0 , Linux x64

**Comment by easrng** [comment]
oh whoops
