### ISSUE TITLE
[Bug] Enafore and all Pinafore variants are broken

### ISSUE THREAD

**Issue by libertyforward1** [enafore/enafore#40]
@easrng Sorry to mention you directly but I'm hoping you might have time to take a look at this. I'm not sure what's happening or if I'm the only one experiencing this, but while the home timeline seems to function properly, almost anything else I've tried besides the settings menu act as if I'm browsing offline. Compose doesn't work because of same alleged offline status.

Strangely, I logged into a secondary account that I don't access very often, and not even the home timeline loads in that case.

Unfortunately this does seem to also affect all the Pinafore variants that I've tried.

Thanks!

**Comment by easrng** [comment]
Can you please try to load one of your timelines, then go to Settings > Logs, and upload a screenshot?

**Comment by libertyforward1** [comment]
Hi there! Unfortunately I am quite embarrassed to admit that I failed to consider a change of internet service, one of the most basic troubleshooting steps. The hotel we've been staying at for the past week evidently has wifi or firewall issues and it never occurred to me until this morning to try our cell service. Voila, it works again! *sigh*
